### ISSUE TITLE
Assertion Failure When Adding Track AnimatedGeometry

### ISSUE THREAD

**Issue by DavidMansolino** [omichel/webots#274]
**Describe the Bug**
Webots raise this assertion when a geometry is added in the `animatedGeometry` field of the `Track` node:
https://github.com/omichel/webots/blob/ff599ed844f0fa4fef529f140ca5a1ecfcad9960/src/webots/nodes/WbTrack.cpp#L491
```
Thread 1 "webots-bin" received signal SIGABRT, Aborted.
0x00007ffff2859428 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:54
54	../sysdeps/unix/sysv/linux/raise.c: Aucun fichier ou dossier de ce type.
(gdb) where
#0  0x00007ffff2859428 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff285b02a in __GI_abort () at abort.c:89
#2  0x00007ffff2851bd7 in __assert_fail_base (fmt=<optimized out>, 
    assertion=assertion@entry=0xc2530f "wrenNode", 
    file=file@entry=0xc2516b "nodes/WbTrack.cpp", line=line@entry=491, 
    function=function@entry=0xc255e0 <WbTrack::updateAnimatedGeometries()::__PRETTY_FUNCTION__> "void WbTrack::updateAnimatedGeometries()") at assert.c:92
#3  0x00007ffff2851c82 in __GI___assert_fail (assertion=0xc2530f "wrenNode", 
    file=0xc2516b "nodes/WbTrack.cpp", line=491, 
    function=0xc255e0 <WbTrack::updateAnimatedGeometries()::__PRETTY_FUNCTION__> "void WbTrack::updateAnimatedGeometries()") at assert.c:101
#4  0x0000000000a1ee9c in WbTrack::updateAnimatedGeometries (
    this=0x7ffede749b20) at nodes/WbTrack.cpp:491
#5  0x0000000000a276cf in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (WbTrack::*)()>::call(void (WbTrack::*)(), WbTrack*, void**) (
    f=(void (WbTrack::*)(WbTrack * const)) 0xa1eca6 <WbTrack::updateAnimatedGeometries()>, o=0x7ffede749b20, arg=0x7fffffffc610)
    at ../../include/qt/QtCore/QtCore/qobjectdefs_impl.h:134
#6  0x0000000000a27368 in QtPrivate::FunctionPointer<void (WbTrack::*)()>::call<QtPrivate::List<>, void>(void (WbTrack::*)(), WbTrack*, void**) (
    f=(void (WbTrack::*)(WbTrack * const)) 0xa1eca6 <WbTrack::updateAnimatedGeom
```

**Steps to Reproduce**
1. Open the `track` simulation.
2. Select the `TRACKED_ROBOT.LEFT_TRACK.ANIMATED_GEOM` field
3. Add a new `Shape` node in this field.
4. Add a new geometry in the `geometry` field of this new `Shape` node => Assertion failure.

**Expected behavior**
We should investigate if this assertion is really needed.

**System**
 - Operating System:Linux Ubuntu 16.04
 - Graphics Card:  NVIDIA GeForce GTX 960

**Comment by DavidMansolino** [comment]
Fixed in #344
