### ISSUE TITLE
Crash When Copy-Pasting an ImageTexture

### ISSUE THREAD

**Issue by DavidMansolino** [omichel/webots#342]
**Describe the Bug**
Webots crashes when copy-pasting an ImageTexture node.

**Steps to Reproduce**
1. Open the khepera3_gripper.wbt world
2. Replace the node in the `RectangelArena.floorAppearance` field with a `PBRAppearance` node.
3. Add an image texture in the `baseColorMap` field and set a valid url.
4. Copy paste the image texture to the `roughnessMap` field => Webots crashes

It is working fine if you add a new image texture node and then assign the same url.

**Expected behavior**
Webots should not crash.

**System**
 - Operating System: Linux Ubuntu 16.04
 - Graphics Card: NVIDIA GeForce GTX 980

**Additional context**
```
Thread 1 "webots-bin" received signal SIGSEGV, Segmentation fault.
0x00007ffff7910e80 in QObjectPrivate::addConnection(int, QObjectPrivate::Connection*) ()
   from /home/david/webots-dev/lib/libQt5Core.so.5
(gdb) where
#0  0x00007ffff7910e80 in QObjectPrivate::addConnection(int, QObjectPrivate::Connection*) ()
   from /home/david/webots-dev/lib/libQt5Core.so.5
#1  0x00007ffff79114c3 in QObjectPrivate::connectImpl(QObject const*, int, QObject const*, void**, QtPrivate::QSlotObjectBase*, Qt::ConnectionType, int const*, QMetaObject const*) ()
   from /home/david/webots-dev/lib/libQt5Core.so.5
#2  0x00007ffff7911865 in QObject::connectImpl(QObject const*, void**, QObject const*, void**, QtPrivate::QSlotObjectBase*, Qt::ConnectionType, int const*, QMetaObject const*) ()
   from /home/david/webots-dev/lib/libQt5Core.so.5
#3  0x00000000009b03f5 in QObject::connect<void (QObject::*)(QObject*), void (WbSimulationWorld::*)(QObject*)> (sender=0x6d0e810, signal=
    (void (QObject::*)(QObject * const, QObject *)) 0x7ffff790eb00 <QObject::destroyed(QObject*)>, receiver=0x6f0d7b0, slot=
    (void (WbSimulationWorld::*)(WbSimulationWorld * const, QObject *)) 0x9afae6 <WbSimulationWorld::removeNodeFromAddedNodeList(QObject*)>, type=Qt::AutoConnection)
    at ../../include/qt/QtCore/QtCore/qobject.h:254
#4  0x00000000009afab2 in WbSimulationWorld::storeAddedNodeIfNeeded (this=0x6f0d7b0, 
    node=0x6d0e810) at engine/WbSimulationWorld.cpp:370
#5  0x0000000000a6cc3b in QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<WbNode*>, void, void (WbWorld::*)(WbNode*)>::call (f=&virtual table offset 120, o=0x6f0d7b0, 
    arg=0x7fffffffcb30) at ../../include/qt/QtCore/QtCore/qobjectdefs_impl.h:134
#6  0x0000000000a6c81f in QtPrivate::FunctionPointer<void (WbWorld::*)(WbNode*)>::call<QtPrivate::List<WbNode*>, void> (f=&virtual table offset 120, o=0x6f0d7b0, arg=0x7fffffffcb30)
    at ../../include/qt/QtCore/QtCore/qobjectdefs_impl.h:167
#7  0x0000000000a6c02b in QtPrivate::QSlotObject<void (WbWorld::*)(WbNode*), QtPrivate::List<WbNode*>, void>::impl (which=1, this_=0x72d9d90, r=0x6f0d7b0, a=0x7fffffffcb30, ret=0x0)
    at ../../include/qt/QtCore/QtCore/qobjectdefs_impl.h:396
#8  0x00007ffff790e4b6 in QMetaObject::activate(QObject*, int, int, void**) ()
   from /home/david/webots-dev/lib/libQt5Core.so.5
#9  0x0000000000b29026 in WbNodeOperations::nodeAdded (this=0x192e070, _t1=0x6d0e810)
    at build/debug/WbNodeOperations.moc.cpp:159
#10 0x0000000000919f12 in WbNodeOperations::importNode (this=0x192e070, parentNode=0x6f77290, 
    field=0x703eec0, itemIndex=-1, filename=..., nodeString=..., avoidIntersections=true, 
    importedNodesNumber=0x0, fromSupervisor=false) at nodes/utils/WbNodeOperations.cpp:186
#11 0x000000000098ad2a in WbSceneTree::pasteInSFValue (this=0x1753d30)
    at scene_tree/WbSceneTree.cpp:335
#12 0x000000000098abf7 in WbSceneTree::paste (this=0x1753d30)
    at scene_tree/WbSceneTree.cpp:321
#13 0x000000000098a839 in WbSceneTree::handleUserCommand (this=0x1753d30, 
    actionKind=WbActionManager::PASTE) at scene_tree/WbSceneTree.cpp:266
#14 0x00000000009944ba in QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<WbActionManager::WbActionKind>, void, void (WbSceneTree::*)(WbActionManager::WbActionKind)>::call
    (f=
    (void (WbSceneTree::*)(WbSceneTree * const, WbActionManager::WbActionKind)) 0x98a7d0 <WbSceneTree::handleUserCommand(WbActionManager::WbActionKind)>, o=0x1753d30, arg=0x7fffffffd020)
    at ../../include/qt/QtCore/QtCore/qobjectdefs_impl.h:134
#15 0x000000000099408d in QtPrivate::FunctionPointer<void (WbSceneTree::*)(WbActionManager::WbActionKind)>::call<QtPrivate::List<WbActionManager::WbActionKind>, void> (f=
    (void (WbSceneTree::*)(WbSceneTree * const, WbActionManager::WbActionKind)) 0x98a7d0 <WbSceneTree::handleUserCommand(WbActionManager::WbActionKind)>, o=0x1753d30, arg=0x7fffffffd020)
    at ../../include/qt/QtCore/QtCore/qobjectdefs_impl.h:167
#16 0x00000000009938af in QtPrivate::QSlotObject<void (WbSceneTree::*)(WbActionManager::WbActionKind), QtPrivate::List<WbActionManager::WbActionKind>, void>::impl (which=1, 
    this_=0x1899ec0, r=0x1753d30, a=0x7fffffffd020, ret=0x0)
    at ../../include/qt/QtCore/QtCore/qobjectdefs_impl.h:396
#17 0x00007ffff790e4b6 in QMetaObject::activate(QObject*, int, int, void**) ()
   from /home/david/webots-dev/lib/libQt5Core.so.5
#18 0x0000000000b12353 in WbActionManager::userWorldEditCommandReceived (this=0x1799bd0, 
    _t1=WbActionManager::PASTE) at build/debug/WbActionManager.moc.cpp:217
#19 0x00000000007a813f in WbActionManager::dispatchUserCommand (this=0x1799bd0)
    at user_commands/WbActionManager.cpp:1047
```

**Comment by DavidMansolino** [comment]
Fixed in #343
